#springboot 自定义视图解析器的配置和缓存工具--当把redis的设置注释掉后，后台的manage就不会进行对redis集群的访问
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    cluster:
      nodes: 192.168.8.130:7001,192.168.8.130:7002,192.168.8.130:7003,192.168.8.130:7004,192.168.8.130:7005,192.168.8.130:7006

server:
  port: 80

# 缓存工具中的软编码
bigad:
  redis:
    key: bigad
  mysql:
    id: 89

# 商品增加，同步solr，软编码url
Httpclient:
  saveurl: http://localhost:8083/save
  deleteurl: http://localhost:8083/delete

# 集群软编码key值
myredis:
  itemkey: itemkey

dubbo:
  application:
    name: ego_manege
  registry:
    address: zookeeper://192.168.8.128:2181

vsftpd:
  host: 192.168.8.129
  port: 21
  username: ftpuser
  password: ftpuser
  basePath: /home/ftpuser/
  filePath: /

