spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ego
    username: root
    password: smallming
mybatis:
  mapper-locations: classpath:mybatis/*.xml
