spring:
  data:
    solr:
      zk-host: 192.168.8.131:2181,192.168.8.131:2182,192.168.8.131:2183
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

search:
  solr:
    collection: collection1

dubbo:
  registry:
    address: zookeeper://192.168.8.128:2181
  application:
    name: ego_search

server:
  port: 8083