spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    cluster:
      nodes: 192.168.8.130:7001,192.168.8.130:7002,192.168.8.130:7003,192.168.8.130:7004,192.168.8.130:7005,192.168.8.130:7006

# 访问此项目的端口
server:
  port: 8080

# 缓存工具中的软编码
bigad:
  redis:
    key: bigad
  mysql:
    id: 89

dubbo:
  registry:
    address: zookeeper://192.168.8.128:2181
  application:
    name: ego_portal


